export const dashboardConfig = {
  title: 'FrontPage Dashboard',
  subtitle: 'A configurable personal homepage for feeds, service health, and weather.',
  bookmarks: [
    {
      id: 'calendar',
      title: 'Google Calendar',
      url: 'https://calendar.google.com/',
      description: 'Meetings, reminders, and shared schedules.',
      tags: ['Planning'],
      starred: true,
    },
    {
      id: 'outlook',
      title: 'Outlook',
      url: 'https://outlook.live.com/',
      description: 'Primary inbox for emails.',
      tags: ['Communication'],
      starred: true,
    },
    {
      id: 'github-home',
      title: 'GitHub',
      url: 'https://github.com/',
      description: 'Repository activity and pull request overview.',
      tags: ['Development'],
      starred: true,
    },
    {
      id: 'docs',
      title: 'Google Docs',
      url: 'https://docs.google.com/',
      description: 'Working documents and shared notes.',
      tags: ['Planning', 'Writing'],
      starred: false,
    },
    {
      id: 'dnd-beyond',
      title: 'D&D Beyond',
      url: 'https://www.dndbeyond.com/',
      description: 'Character sheets and campaign management.',
      tags: ['Gaming'],
      starred: false,
    },
    {
      id: 'gmail',
      title: 'Gmail',
      url: 'https://mail.google.com/',
      description: 'Secondary inbox for emails.',
      tags: ['Communication'],
      starred: false,
    },
    {
      id: 'youtube',
      title: 'YouTube',
      url: 'https://www.youtube.com/',
      description: 'Video content and subscriptions.',
      tags: ['Entertainment'],
      starred: false,
    },
    {
      id: 'reddit',
      title: 'Reddit',
      url: 'https://www.reddit.com/',
      description: 'News, discussions, and communities.',
      tags: ['Entertainment', 'News'],
      starred: false,
    },
    {
      id: 'goodreads',
      title: 'Goodreads',
      url: 'https://www.goodreads.com/',
      description: 'Book tracking and reviews.',
      tags: ['Entertainment'],
      starred: false,
    },
    {
      id: 'amazon',
      title: 'Amazon',
      url: 'https://www.amazon.co.uk/',
      description: 'Online shopping and product reviews.',
      tags: ['Shopping'],
      starred: false,
    },
    {
      id: 'op.gg',
      title: 'OP.GG',
      url: 'https://www.op.gg/',
      description: 'League of Legends stats and rankings.',
      tags: ['Gaming'],
      starred: false,
    }
  ],
  rss: {
    corsProxyUrl: 'https://api.allorigins.win/raw?url=',
    feeds: [
      {
        id: 'morning-brew',
        name: 'Morning Brew',
        url: 'https://feeds.megaphone.fm/MOBI8777994188',
        description: 'Daily business news from Morning Brew.',
        itemLimit: 0,
      },
      {
        id: 'bbc-uk',
        name: 'BBC UK News',
        url: 'https://feeds.bbci.co.uk/news/uk/rss.xml',
        description: 'UK headlines from BBC News.',
        itemLimit: 0,
      },
      {
        id: 'marketwatch',
        name: 'MarketWatch',
        url: 'https://feeds.content.dowjones.io/public/rss/mw_topstories',
        description: 'Top financial news from MarketWatch.',
        itemLimit: 0,
      },
    ],
  },
  llm: {
    summaryApiUrl: 'https://api.openai.com/v1/chat/completions',
    model: 'gpt-4.1-mini',
    timeoutMs: 200000,
    systemPrompt: 'You summarize RSS feed intelligence for a dashboard. Be factual, concise, and avoid speculation. Keep your summary to 3 or 4 sentences max.',
    headers: {},
  },
  services: [
    {
      name: 'GitHub API',
      url: 'https://api.github.com',
      method: 'GET',
      timeoutMs: 4000,
      description: 'General GitHub API availability.',
    },
    {
      name: 'Cloudflare Status API',
      url: 'https://www.cloudflarestatus.com/api/v2/status.json',
      method: 'GET',
      timeoutMs: 4000,
      description: 'Cloudflare public status summary.',
    },
  ],
  weather: {
    label: 'London',
    latitude: 51.5072,
    longitude: -0.1276,
    timezone: 'Europe/London',
    temperatureUnit: 'celsius',
    windspeedUnit: 'kmh',
  },
}
