export const dashboardConfig = {
  title: 'FrontPage Dashboard',
  subtitle: 'A configurable personal homepage for feeds, service health, and weather.',
  bookmarks: [
    {
      id: 'github-home',
      title: 'GitHub',
      url: 'https://github.com/',
      description: 'Repository activity and pull request overview.',
      tags: ['Development', 'Daily'],
      starred: true,
    },
    {
      id: 'gmail',
      title: 'Gmail',
      url: 'https://mail.google.com/',
      description: 'Primary inbox and notifications.',
      tags: ['Communication', 'Daily'],
      starred: true,
    },
    {
      id: 'calendar',
      title: 'Google Calendar',
      url: 'https://calendar.google.com/',
      description: 'Meetings, reminders, and shared schedules.',
      tags: ['Planning', 'Daily'],
      starred: true,
    },
    {
      id: 'docs',
      title: 'Google Docs',
      url: 'https://docs.google.com/',
      description: 'Working documents and shared notes.',
      tags: ['Planning', 'Writing'],
      starred: false,
    },
    {
      id: 'jira',
      title: 'Jira',
      url: 'https://www.atlassian.com/software/jira',
      description: 'Tickets, sprint boards, and backlog tracking.',
      tags: ['Operations', 'Planning'],
      starred: false,
    },
    {
      id: 'statuspage',
      title: 'Atlassian Status',
      url: 'https://status.atlassian.com/',
      description: 'Service incidents and platform availability.',
      tags: ['Operations', 'Monitoring'],
      starred: false,
    },
    {
      id: 'cloudflare',
      title: 'Cloudflare Dashboard',
      url: 'https://dash.cloudflare.com/',
      description: 'DNS, edge controls, and zero trust settings.',
      tags: ['Infrastructure', 'Security'],
      starred: false,
    },
    {
      id: 'grafana',
      title: 'Grafana',
      url: 'https://grafana.com/',
      description: 'Dashboards, alerts, and observability views.',
      tags: ['Monitoring', 'Infrastructure'],
      starred: false,
    },
  ],
  rss: {
    corsProxyUrl: 'https://api.allorigins.win/raw?url=',
    feeds: [
      {
        id: 'morning-brew',
        name: 'Morning Brew',
        url: 'https://feeds.megaphone.fm/MOBI8777994188',
        description: 'Daily business news from Morning Brew.',
        itemLimit: 0,
      },
      {
        id: 'bbc-uk',
        name: 'BBC UK News',
        url: 'https://feeds.bbci.co.uk/news/uk/rss.xml',
        description: 'UK headlines from BBC News.',
        itemLimit: 0,
      },
    ],
  },
  services: [
    {
      name: 'GitHub API',
      url: 'https://api.github.com',
      method: 'GET',
      timeoutMs: 4000,
      description: 'General GitHub API availability.',
    },
    {
      name: 'Cloudflare Status API',
      url: 'https://www.cloudflarestatus.com/api/v2/status.json',
      method: 'GET',
      timeoutMs: 4000,
      description: 'Cloudflare public status summary.',
    },
  ],
  weather: {
    label: 'London',
    latitude: 51.5072,
    longitude: -0.1276,
    timezone: 'Europe/London',
    temperatureUnit: 'celsius',
    windspeedUnit: 'kmh',
  },
}
